Repository googleapis/python-domains, pull requests merged in 2021-04, with the labels that each got.

#11 chore: start tracking obsolete files
  synth.metadata
Labels: api: domains, cla: yes, context: full

#12 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: domains, cla: yes, context: full

#13 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: domains, cla: yes, context: full, samples

#15 chore: prevent normalization of semver versioning
  setup.py
Labels: api: domains, cla: yes

#14 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: domains, automerge, cla: yes, context: full

#16 chore(revert): revert preventing normalization
  setup.py
Labels: api: domains, automerge, cla: yes
